### ISSUE TITLE
SystemUI FC when PIE is enabled

### ISSUE THREAD

**Issue by kashifmin** [PAC-ROM/android_frameworks_base#1]
SystemUI FCs continuously when pie controls enabled and while accessing "Style and Dimension" option in settings.
Logcat: http://pastebin.com/Z6HsKgzw

**Comment by mallardduck** [comment]
We take our bug reports on our jira.

jira.pac-rom.com

On Thu, Oct 23, 2014 at 10:23 AM, kashifmin notifications@github.com
wrote:

> SystemUI FCs continuously when pie controls enabled and while accessing
> "Style and Dimension" option in settings.
> Logcat: http://pastebin.com/Z6HsKgzw
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PAC-man/android_frameworks_base/issues/1.

## 

-Dan Pock

**Comment by Nick0703** [comment]
Submit it to jira.

**Comment by ShevT** [comment]
How to fix this problem on kitkat?
This patch does not solve it.
I can not give people the firmware with this problem.
http://jira.pac-rom.com/ - Service Unavailable
